"""
Campaign Activity Logger & Report Exporter (TXT & CSV Formats)
"""

import os
from datetime import datetime
from config.database import get_connection


def _ensure_clean_logs_table(conn, cursor):
    """
    Guarantees table schema with all required columns.
    """
    cursor.execute("PRAGMA table_info(campaign_logs)")
    existing_cols = [c[1] for c in cursor.fetchall()]
    required_cols = {"campaign_id", "queue_id", "recipient_email", "sender_email", "status", "error_reason", "created_at"}

    # Agar purani incomplete table ho toh rebuild kar lo
    if existing_cols and not required_cols.issubset(set(existing_cols)):
        cursor.execute("DROP TABLE IF EXISTS campaign_logs")
        conn.commit()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS campaign_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            campaign_id INTEGER,
            queue_id INTEGER,
            recipient_email TEXT,
            sender_email TEXT,
            status TEXT,
            error_reason TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.commit()


def log_campaign_event(campaign_id, queue_id, email, account_email, status, error_reason=None):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        _ensure_clean_logs_table(conn, cursor)
        cursor.execute(
            """
            INSERT INTO campaign_logs (campaign_id, queue_id, recipient_email, sender_email, status, error_reason)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (campaign_id, queue_id, email, account_email, status, error_reason)
        )
        conn.commit()
    except Exception as e:
        print(f"[Logging Error] {e}")
    finally:
        conn.close()


def export_campaign_report(campaign_id, export_txt=True):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        _ensure_clean_logs_table(conn, cursor)
        cursor.execute(
            """
            SELECT id, name, status, total_contacts, completed_count, failed_count, pending_count, created_at
            FROM campaigns WHERE id = ?
            """,
            (campaign_id,)
        )
        camp = cursor.fetchone()
        if not camp:
            print(f"\n[Error] Campaign #{campaign_id} not found.")
            return None

        cursor.execute(
            """
            SELECT id, recipient_email, sender_email, status, error_reason, created_at
            FROM campaign_logs
            WHERE campaign_id = ?
            ORDER BY id ASC
            """,
            (campaign_id,)
        )
        logs = cursor.fetchall()

        reports_dir = os.path.join(os.getcwd(), "reports")
        os.makedirs(reports_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Plain Text Audit Report (.txt)
        txt_name = f"Campaign_{campaign_id}_Report_{timestamp}.txt"
        txt_path = os.path.join(reports_dir, txt_name)

        with open(txt_path, mode="w", encoding="utf-8") as f:
            f.write("================================================================================\n")
            f.write("                       CAMPAIGN AUDIT & PERFORMANCE REPORT                      \n")
            f.write("================================================================================\n\n")
            f.write(f"Campaign ID       : {camp[0]}\n")
            f.write(f"Campaign Name     : {camp[1]}\n")
            f.write(f"Status            : {camp[2]}\n")
            f.write(f"Total Contacts    : {camp[3]}\n")
            f.write(f"Completed Drafts  : {camp[4]}\n")
            f.write(f"Failed Drafts     : {camp[5]}\n")
            f.write(f"Pending Drafts    : {camp[6]}\n")
            f.write(f"Created At        : {camp[7]}\n\n")
            f.write("--------------------------------------------------------------------------------\n")
            f.write(f"{'LOG ID':<8} | {'RECIPIENT':<30} | {'STATUS':<10} | {'TIMESTAMP':<20}\n")
            f.write("--------------------------------------------------------------------------------\n")
            
            if not logs:
                f.write("No individual logs recorded for this campaign.\n")
            else:
                for row in logs:
                    lid, rec, snd, stat, err, ts = row
                    err_info = f" (Error: {err})" if err else ""
                    f.write(f"{lid:<8} | {rec or 'N/A':<30} | {stat + err_info:<10} | {ts}\n")

            f.write("\n================================================================================\n")
            f.write("                     Generated by Grace Outreach Assistant                      \n")
            f.write("================================================================================\n")

        print("\n" + "=" * 70)
        print("                 CAMPAIGN REPORT EXPORTED (.TXT)")
        print("=" * 70)
        print(f"File Saved: {txt_path}")
        print("=" * 70)
        return txt_path
    finally:
        conn.close()
